### ISSUE TITLE
polyfill classes are not available.

### ISSUE THREAD

**Issue by rquadling** [spindle/spindle-types#2]
Specifically, I wanted to use the DateTimeInterface in a PHP5.4 environment.

Following the pattern of polly-filling used by Symfony, it would seem the `composer.json` file is missing a `"files"` entry.

The Symfony Polyfill PHP5.5 composer.json file contains

```
    "autoload": {
        "psr-4": { "Symfony\\Polyfill\\Php55\\": "" },
        "files": [ "bootstrap.php" ]
    },
```

This results in the appropriate functions being loaded/registered automatically, with no need to refer to a particular namespace.

**Comment by hirak** [comment]
That can apply global function only. It's impossible for \DateTimeInterface.
- \DateTime must implements \DateTimeInterface
- \DateTimeImmutable must implements \DateTimeInterface

``` php
<?php
// PHP5.3
interface DateTimeInterface
{
}

function doSomething(DateTimeInterface $date) {
}

doSomething(new DateTime); // Fatal Error
```

**Comment by rquadling** [comment]
Yeah. Doh!
